# Generated by Django 5.2.11 on 2026-02-16 10:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='selling_price',
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('expiry_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='drugs.drug')),
            ],
            options={
                'verbose_name_plural': 'Batches',
                'ordering': ['expiry_date'],
            },
        ),
    ]
