# Generated by Django 5.2.11 on 2026-06-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_remove_drug_expiry_date_remove_drug_purchase_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='dispensing_strategy',
            field=models.CharField(choices=[('FEFO', 'FEFO - First Expiry, First Out'), ('FIFO', 'FIFO - First In, First Out')], default='FEFO', max_length=4),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
