# Generated by Django 5.2.11 on 2026-06-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0003_drug_dispensing_strategy_alter_batch_batch_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
