# Generated by Django 5.2.11 on 2026-07-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_supplierpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierpayment',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer')], default='CASH', max_length=10),
        ),
    ]
