# Generated by Django 5.2.11 on 2026-02-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PHARMACIST', 'Pharmacist')], default='PHARMACIST', max_length=20),
        ),
    ]
