# Generated by Django 5.2.11 on 2026-02-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='batch_number',
            field=models.CharField(default='LEGACY', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
