# Generated by Django 5.2.11 on 2026-06-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_purchaseitem_batch_number_purchaseitem_selling_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='batch_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
