# Generated by Django 5.2.11 on 2026-06-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_alter_purchaseitem_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='returned_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
