#!/usr/bin/env python
"""One-time: generate the license signing keypair.

Run this ONCE, on your own machine, before building for clients:

    python tools/gen_keys.py

It writes two files:

  * private_key.json        -> your SECRET signing key. Keep it safe, back it
                               up, and NEVER ship or commit it. It is the only
                               thing that can issue valid licenses. (Already in
                               .gitignore.)
  * licensing/public_key.py -> the public key, embedded in the app. Safe to
                               commit and ship.

If you re-run this, every previously issued license stops working (the public
key changes). Only do that if your private key was lost or leaked.
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from licensing import _rsa  # noqa: E402

PRIVATE_KEY_FILE = ROOT / "private_key.json"
PUBLIC_KEY_FILE = ROOT / "licensing" / "public_key.py"


def main() -> int:
    if PRIVATE_KEY_FILE.exists():
        reply = input(
            f"{PRIVATE_KEY_FILE} already exists. Overwrite and invalidate ALL "
            "existing licenses? [y/N] "
        ).strip().lower()
        if reply != "y":
            print("Aborted.")
            return 1

    print("Generating a 2048-bit RSA keypair (a few seconds)…")
    key = _rsa.generate_keypair(2048)

    PRIVATE_KEY_FILE.write_text(json.dumps(key, indent=2), encoding="utf-8")
    try:
        PRIVATE_KEY_FILE.chmod(0o600)
    except OSError:
        pass

    PUBLIC_KEY_FILE.write_text(
        '"""Embedded RSA public key used to verify license files.\n\n'
        "This file is SAFE to commit and ship — it contains only the *public* key.\n"
        "It is (re)generated by ``tools/gen_keys.py``.\n"
        '"""\n\n'
        "# Generated by tools/gen_keys.py\n"
        f"PUBLIC_KEY_N = {key['n']}\n"
        f"PUBLIC_KEY_E = {key['e']}\n",
        encoding="utf-8",
    )

    print(f"Wrote private key -> {PRIVATE_KEY_FILE}  (keep this secret!)")
    print(f"Wrote public key  -> {PUBLIC_KEY_FILE}")
    print("\nDone. You can now sign licenses with tools/sign_license.py.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
