# Generated by Django 5.2.11 on 2026-06-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_remove_sale_final_amount_sale_is_refunded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='returned_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
